<main class="admin">
    <h3>Ajouter un nouvelle article à la boutique</h3>
    <form method="post">
        <label for="newNameArticle">Nom de l'article</label>
        <input type="text" name="newNameArticle">
        <label for="newImgArticle">Url de l'image</label>
        <input type="text" name="newImgArticle">
        <label for="newTextArticle">Description du produit</label>
        <input type="text" name="newTextArticle">
        <label for="newPriceArticle">Prix de l'article</label>
        <input type="text" name="newPriceArticle">
        <button value="create" name="action">Envoyer</button>
        <input type="hidden" name="id_article" value="">
    </form>
</main>
