<footer>
    <div class="infoSite">
        <ul>
            <li>
                <i class="fa fa-lock" aria-hidden="true"></i>
                <p>
                    Payement Securisé
                </p>
            </li>
            <li>
                <i class="fa fa-phone" aria-hidden="true"></i>
                <p>
                    Service Clients
                </p>
            </li>
            <li>
                <i class="fa fa-check-circle-o" aria-hidden="true"></i>
                <p>
                    Garantie Qualité
                </p>
            </li>
            <li>
                <i class="fa fa-truck" aria-hidden="true"></i>
                <p>
                    Livraison Rapide
                </p>
            </li>
            <li>
                <i class="fa fa-paypal" aria-hidden="true"></i>
                <p>
                    Payement PayPal
                </p>
            </li>
        </ul>
    </div>
    <div class="middleFooter">
        <div class="social">
            <h4>Nos résaux sociaux</h4>
            <ul>
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i></a></li>
            </ul>
        </div>
        <div class="contact">
            <h4>Contact</h4>
            <ul>
                <li><a href="#"><i class="fa fa-home" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i></a></li>
            </ul>
        </div>
        <div class="compte">
            <h4>Mon compte</h4>
            <ul>
                <li><a href="#">Mes commandes</a></li>
                <li><a href="index.php?page=panier">Mon panier</a></li>
                <li><a href="#">Mon profil</a></li>
                <li><a href="#">Mes tickets</a></li>
                <li><a href="index.php?page=logout">Se déconnecter</a></li>
            </ul>
        </div>
    </div>
    <div class="licence">
        <p>
            Ce site bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
            bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
            bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
            bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
            bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
            bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
        </p>
    </div>
</footer>
