<footer>
    <div class="infoSite">
        <ul>
            <li>
                <i class="fa fa-lock" aria-hidden="true"></i>
                <p>
                    Payement Securisé
                </p>
            </li>
            <li>
                <i class="fa fa-phone" aria-hidden="true"></i>
                <p>
                    Service Clients
                </p>
            </li>
            <li>
                <i class="fa fa-check-circle-o" aria-hidden="true"></i>
                <p>
                    Garantie Qualité
                </p>
            </li>
            <li>
                <i class="fa fa-truck" aria-hidden="true"></i>
                <p>
                    Livraison Rapide
                </p>
            </li>
            <li>
                <i class="fa fa-paypal" aria-hidden="true"></i>
                <p>
                    Payement PayPal
                </p>
            </li>
        </ul>
    </div>
    <div class="middleFooter">
        <div class="social">
            <ul>
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i></a></li>
            </ul>
        </div>
        <div class="contact">
            <ul>
                <li><a href="#"><i class="fa fa-home" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-envelope-o" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-phone" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="licence">
        <p>
            Ce site bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
        </p>
    </div>
</footer>
