<header>
    <div class="offre">
        <p>Dès 50€ d'achat la livraison est offerte</p>
    </div>
    <div class="middleHeader">
        <img src="https://heartofthorns.guildwars2.com/assets/images/logos/guild-wars.png" alt="logo" />
        <div class="panier">
            <p>
                Mon panier <i class="fa fa-shopping-cart" aria-hidden="true"></i> ... €
            </p>
        </div>
    </div>
    <nav>
        <ul>
            <li>
                <a href="#">News</a>
            </li>
            <li>
                <a href="#">Tutos</a>
            </li>
            <li>
                <a href="#">Boutique</a>
            </li>
            <li>
                <a href="#">Connexion</a>
            </li>
        </ul>
    </nav>
    <div class="search">
        <label>Rechercher : </label>
        <input type="text" name="search">
    </div>
</header>
