<main class="home">
    <section class="slider">
        <!-- Code flexslider -->
        <div class="flexslider">
            <ul class="slides">
                <li>
                    <img src="https://cdna.artstation.com/p/users/covers/000/015/838/default/7a9c5412240c83cc05a93fcc4e403194.jpg?1463521487" alt="Photo du slider" />
                </li>
                <li>
                    <img src="https://i.imgur.com/LiPaicq.jpg" alt="Photo du slider" />
                </li>
                <li>
                    <img src="https://cdna.artstation.com/p/users/covers/000/060/408/default/1080c2db41cee5fceae1583e5074e4bb.jpg?1500587160" alt="Photo du slider" />
                </li>
            </ul>
        </div>
        <!-- Fin code flexslider -->
    </section>
    <div class="articles">
        <h3>Nos articles les mieux notés</h3>
        <div class="bestArticle">
            <?php require('apps/bestArticle.php'); ?>
        </div>
        <h3>Nos articles favoris !</h3>
        <div class="aleatoireArticle">
            <?php require('apps/randomArticle.php'); ?>
        </div>
    </div>
</main>
