<main class="login">
    <img src="http://i1.wp.com/metatrone.fr/wp-content/uploads/2015/07/GW2Logo.png?fit=256%2C256" alt="logo" />
    <h4>Connexion au compte</h4>
    <form method="post" action="">
        <label for="pseudo">Nom d'utilisateur</label>
        <input type="text" name="pseudo">
        <label for="password">Mot de passe</label>
        <input type="password" name="password">
        <button value="login" name="action">Se connecter !</button>
    </form>
    <a href="index.php?page=registation">S'inscrire</a>
</main>
