<main class="shopPanier">
    <div class="left">
        <?php require('apps/affichagePanier.php') ?>
    </div>
    <div class="right">
        <h5>Total Commande</h5>
        <p>
            99.98 €
        </p>
        <h6>Commande</h6>
        <p>
            79.98 €
        </p>
        <h6>Frais de port</h6>
        <p>
            20 €
        </p>
        <form method="post">
            <button type="button" name="button">Commander</button>
        </form>
    </div>
</main>
