<main class="registation">
    <h4>Inscription</h4>
    <form method="post">
        <label for="email">Email</label>
        <input type="text" name="email">
        <label for="pseudo">Pseudo</label>
        <input type="text" name="pseudo">
        <label for="password">Mot de passe</label>
        <input type="password" name="password">
        <button value="create" name="action">crée mon compte</button>
    </form>
</main>
