<main class="registation">
    <h4>Inscription</h4>
    <form method="post">
        <label for="email">Email</label>
        <input type="text" name="email">
        <label for="pseudoInsc">Pseudo</label>
        <input type="text" name="pseudoInsc">
        <label for="passwordInsc">Mot de passe</label>
        <input type="password" name="passwordInsc">
        <a href="#">crée mon compte</a>
    </form>
</main>
