<!DOCTYPE html>
<html lang="zxx">
    <head>
        <meta charset="utf-8">
        <title>ProjFinal</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" href="public/styles/normalize.css">
        <link rel="stylesheet" type="text/css" href="public/styles/font-awesome.min.css"/>
        <link rel="stylesheet" href="public/styles/flexslider.css">
        <link rel="stylesheet" href="public/styles/style.css" />
        <script src="public/scripts/jquery-3.2.1.min.js"></script>
        <script src="public/scripts/jquery.flexslider-min.js"></script>
        <script>
    		$(window).on('load', function() {
    			$('.flexslider').flexslider({
    				directionNav: false,
    				controlNav: false
    			});
    		});
    	</script>
    </head>
    <body>
        <?php require('apps/header.php'); ?>
        <?php require('apps/content.php'); ?>
        <?php require('apps/footer.php'); ?>
    </body>
</html>
