<!DOCTYPE html>
<html lang="zxx">
    <head>
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" type="text/css" href="public/styles/font-awesome.min.css"/>
        <link rel="stylesheet" href="public/styles/style.css" />
        <meta charset="utf-8">
        <title>ProjFinal</title>
    </head>
    <body>
        <?php require('apps/header.php'); ?>
        <?php //require('apps/content.php'); ?>
        <?php require('apps/footer.php'); ?>
    </body>
</html>
